// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Models;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(SecretContext))]
    [Migration("20230522085711_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebApplication1.Models.Secret", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("createdAt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("expiresAt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("hash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("remainingViews")
                        .HasColumnType("int");

                    b.Property<string>("secretText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Secrets");
                });
#pragma warning restore 612, 618
        }
    }
}
